version: "2"
services:
   namenode:
      image: flokkr/hadoop:${VERSION}
      command: ["hdfs", "namenode"]
      hostname: namenode
      ports:
         - 9870:9870
      env_file:
        - ./config
      environment:
          ENSURE_NAMENODE_DIR: "/tmp/hadoop-hadoop/dfs/name"
   datanode:
      image: flokkr/hadoop:${VERSION}
      command: ["hdfs", "datanode"]
      links:
         - namenode
      env_file:
        - ./config
