version: "3"
services:
   consul:
     hostname: consul
     image: consul
     ports:
       - 8500:8500
     command: ["agent","-dev","-ui","-client","0.0.0.0"]
   namenode:
      image: flokkr/hadoop-hdfs-namenode:ozone
      hostname: namenode
      ports:
         - 9870:9870
      environment:
          ENSURE_NAMENODE_DIR: /data/namenode
      env_file:
         - ./docker-config
      command: ["/opt/hadoop/bin/hdfs","namenode"]
   datanode:
      image: flokkr/hadoop-hdfs-datanode:ozone
      ports:
        - 9864
      env_file:
         - ./docker-config
      command: ["/opt/hadoop/bin/hdfs","datanode"]
   ksm:
      hostname: ksm
      image: flokkr/hadoop:ozone
      ports:
         - 9874:9874
      env_file:
          - ./docker-config
      command: ["/opt/hadoop/bin/hdfs","ksm"]
   scm:
      hostname: scm
      image: flokkr/hadoop:ozone
      ports:
         - 9876:9876
      env_file:
          - ./docker-config
      command: ["/opt/hadoop/bin/hdfs","scm"]
   prometheus:
     image: prom/prometheus
     ports:
       - 9090:9090
     volumes:
       - "./prometheus.yml:/tmp/prometheus.yml"
     command: ["-storage.local.path=/tmp/data","-config.file=/tmp/prometheus.yml"]
