version: "3"
services:
   c2namenode1:
      image: flokkr/hadoop:${VERSION}
      hostname: c2namenode1
      ports:
         - 9872:9870
      env_file:
        - ./c2config
      environment:
          ENSURE_NAMENODE_DIR: "/tmp/hadoop-hadoop/dfs/name"
          SLEEP_SECONDS: 20
      command: ["hdfs", "namenode"]
   c2namenode2:
      image: flokkr/hadoop:${VERSION}
      hostname: c2namenode2
      ports:
         - 9873:9870
      env_file:
        - ./c2config
      environment:
          ENSURE_STANDBY_NAMENODE_DIR: "/tmp/hadoop-hadoop/dfs/name"
          SLEEP_SECONDS: 40
      command: ["hdfs", "namenode"]
   c2journal1:
      image: flokkr/hadoop:${VERSION}
      hostname: journal1
      env_file:
        - ./c2config
      command: ["hdfs", "journalnode"]
   c2journal2:
      image: flokkr/hadoop:${VERSION}
      hostname: journal2
      env_file:
        - ./c2config
      command: ["hdfs", "journalnode"]
   c2journal3:
      image: flokkr/hadoop:${VERSION}
      hostname: journal3
      env_file:
        - ./c2config
      command: ["hdfs", "journalnode"]
   c2datanode:
      image: flokkr/hadoop:${VERSION}
      command: ["hdfs", "datanode"]
      env_file:
        - ./c2config
      environment:
         SLEEP_SECONDS: 50
   c2activator:
      image: flokkr/hadoop:${VERSION}
      command: ["hdfs", "haadmin", "-transitionToActive", "nn1"]
      env_file:
        - ./c2config
      environment:
         SLEEP_SECONDS: 60
