version: "2"
services:
   namenode:
      image: flokkr/hadoop:${HADOOP_VERSION}
      hostname: namenode
      command: ["hdfs", "namenode"]
      ports:
        - 9870:9870
      env_file:
        - ./config
      environment:
        ENSURE_NAMENODE_DIR: "/tmp/hadoop-hadoop/dfs/name"
      volumes:
        - ./testdata:/opt/testdata
   datanode:
      image: flokkr/hadoop:${HADOOP_VERSION}
      command: ["hdfs", "datanode"]
      env_file:
        - ./config
   resourcemanager:
      image: flokkr/hadoop:${HADOOP_VERSION}
      hostname: resourcemanager
      command: ["yarn", "resourcemanager"]
      ports:
         - 8088:8088
      env_file:
        - ./config
      volumes:
        - ./testdata:/opt/testdata
   nodemanager:
      image: flokkr/hadoop:${HADOOP_VERSION}
      command: ["yarn","nodemanager"]
      env_file:
        - config
   sparkhistory:
      image: flokkr/spark:${SPARK_VERSION}
      command: ["/opt/spark/bin/spark-class","org.apache.spark.deploy.history.HistoryServer"]
      ports:
        - 18080:18080
      environment:
         SLEEP_SECONDS: 30
      env_file:
        - ./config
   sparklogdirinit:
      image: flokkr/hadoop:${HADOOP_VERSION}
      volumes:
         - ./init-hdfs.sh:/usr/bin/init-hdfs.sh
      command: ["/usr/bin/init-hdfs.sh"]
      environment:
         SLEEP_SECONDS: 15
      env_file:
        - config
