version: "2"
services:
   nna:
      image: flokkr/hadoop:${VERSION}
      hostname: nna
      ports:
         - 9870:9870
      env_file:
        - ./config
      environment:
          ENSURE_NAMENODE_DIR: "/tmp/hadoop-hdfs/dfs/name"
          ENSURE_NAMENODE_CLUSTERID: "c1"
      command: ["hdfs","namenode"]
   nnb:
      image: flokkr/hadoop:${VERSION}
      hostname: nnb
      ports:
         - 9871:9870
      env_file:
        - ./config
      environment:
          ENSURE_NAMENODE_DIR: "/tmp/hadoop-hdfs/dfs/name"
          ENSURE_NAMENODE_CLUSTERID: "c1"
      command: ["hdfs","namenode"]
   datanode:
      image: flokkr/hadoop:${VERSION}
      env_file:
        - ./config
      command: ["hdfs","datanode"]
