version: "2"
services:
   nnx:
      image: flokkr/hadoop:${VERSION}
      hostname: nnx
      ports:
         - 9870:9870
      env_file:
         - ./configx
      environment:
          ENSURE_NAMENODE_DIR: "/tmp/hadoop-hadoop/dfs/name"
      command: ["hdfs","namenode"]
   datanodex:
      image: flokkr/hadoop:${VERSION}
      env_file:
        - ./configx
      command: ["hdfs","datanode"]
   nny:
      image: flokkr/hadoop:${VERSION}
      hostname: nny
      ports:
         - 9871:9870
      env_file:
         - ./configy
      environment:
          ENSURE_NAMENODE_DIR: "/tmp/hadoop-hadoop/dfs/name"
      command: ["hdfs","namenode"]
   datanodey:
      image: flokkr/hadoop:${VERSION}
      env_file:
        - ./configy
      command: ["hdfs","datanode"]
   
