version: "3"
services:
   namenode:
      image: flokkr/hadoop:ozone
      hostname: namenode
      command: ["hdfs", "namenode"]
      ports:
         - 9870:9870
      environment:
          ENSURE_NAMENODE_DIR: /data/namenode
      env_file:
         - ./config
   datanode:
      image: flokkr/hadoop:ozone
      command: ["hdfs", "datanode"]
      ports:
        - 9864
      env_file:
         - ./config        
   ksm:
      image: flokkr/hadoop:ozone
      hostname: ksm
      command: ["hdfs","ksm"]
      ports:
         - 9874:9874
      env_file:
          - ./config
      environment:
         ENSURE_KSM_INITIALIZED: /data/metadata/ksm/current/VERSION
   scm:
      hostname: scm
      image: flokkr/hadoop:ozone
      command: ["hdfs","scm"]
      ports:
         - 9876:9876
      env_file:
          - ./config
      environment:
         ENSURE_SCM_INITIALIZED: /data/metadata/scm/current/VERSION
