version: "2"
services:
   namenode:
      image: flokkr/hadoop:latest
      hostname: namenode
      command: ["hdfs","namenode"]
      ports:
         - 9870:9870
      env_file:
        - ./config
      environment:
          ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
   datanode:
      image: flokkr/hadoop:latest
      command: ["hdfs", "datanode"]
      env_file:
        - ./config
   resourcemanager:
      image: flokkr/hadoop:latest
      hostname: resourcemanager
      command: ["yarn", "resourcemanager"]
      ports:
         - 8088:8088
      env_file:
        - ./config
   nodemanager:
      image: flokkr/hadoop:latest
      command: ["yarn", "nodemanager"]
      env_file:
        - ./config
   zookeeper:
      image: flokkr/zookeeper
      hostname: zookeeper
      environment:
        ZOO.CFG_clientPort: 2181
        ZOO.CFG_dataDir: /tmp/zookeeper
#        ZOO.CFG_server.1: zookeeper1:2888:3888
#        ZOO.CFG_server.2: zookeeper2:2888:3888
#        ZOO.CFG_server.3: zookeeper3:2888:3888
#        ZOO.CFG_initLimit: 5
#        ZOO.CFG_syncLimit: 2
   metastoredb:
     image: postgres
     environment:
       POSTGRES_PASSWORD: rootpwd
       POSTGRES_DB: metastore
       POSTGRES_USER: hive
   metastore:
     image: flokkr/hive
     command: ["hive","--service", "metastore"]
     env_file:
        - ./config
   hiveserver2:
     image: flokkr/hive
     command: ["hive","--service", "hiveserver2"]
     ports:
        - 10002:10002
     env_file:
        - ./config
   llap:
     image: flokkr/hive
     command: ["hive","--service", "llap"]
     env_file:
        - ./config
